// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjYuPTtgJAzNkgfP7hz9BwInZV6-NUqCs',
    appId: '1:88107289644:web:10aa5bc32960ae74b0d589',
    messagingSenderId: '88107289644',
    projectId: 'chatapp-2bef9',
    authDomain: 'chatapp-2bef9.firebaseapp.com',
    storageBucket: 'chatapp-2bef9.appspot.com',
    measurementId: 'G-KG9KMSJ0RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ45T8GiqZRrIIhtPJ7VqaFGyJ5oNEKbs',
    appId: '1:88107289644:android:01c645d63231dff5b0d589',
    messagingSenderId: '88107289644',
    projectId: 'chatapp-2bef9',
    storageBucket: 'chatapp-2bef9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyc4twXxt-PHENhfJOWh4dKVwEWD-qlBg',
    appId: '1:88107289644:ios:9c59313a062b397bb0d589',
    messagingSenderId: '88107289644',
    projectId: 'chatapp-2bef9',
    storageBucket: 'chatapp-2bef9.appspot.com',
    iosClientId: '88107289644-kutahptrvc24o3l3b3kr15921ru4cbn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyc4twXxt-PHENhfJOWh4dKVwEWD-qlBg',
    appId: '1:88107289644:ios:7f27cd5141a0750fb0d589',
    messagingSenderId: '88107289644',
    projectId: 'chatapp-2bef9',
    storageBucket: 'chatapp-2bef9.appspot.com',
    iosClientId: '88107289644-p7rhgpmm2upr5rv006qgsn9nulggm3gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo1.RunnerTests',
  );
}
